{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels-ui" . | nindent 4 }}
{{- with .Values.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels-ui" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels-ui" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      {{- if .Values.ui.nginxConfigMap.enabled }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "chart.fullname" . }}-ui-nginx-config
      {{- end }}
      containers:
      - image: {{ .Values.ui.image.repository }}:{{ default .Chart.AppVersion .Values.ui.image.tag }}
        name: envoy-xds-controller-ui
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        {{- if .Values.ui.nginxConfigMap.enabled }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/templates/nginx.conf
          subPath: template.conf
        {{- end }}
        env:
          - name: API_PROXY_PASS
            value: "{{ .Values.ui.cacheAPI }}"
          - name: GRPC_API_PROXY_PASS
            value: "{{ .Values.ui.resourceAPI }}"
          {{- if .Values.auth.enabled }}
          - name: VITE_OIDC_ENABLED
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_ENABLED

          - name: VITE_OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_CLIENT_ID

          - name: VITE_OIDC_AUTHORITY
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_ISSUER_URL

          - name: VITE_OIDC_SCOPE
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_SCOPE

          - name: VITE_OIDC_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_REDIRECT_URI
          {{- end }}
        {{- with .Values.ui.envs }}
          {{- tpl . $ | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.ui.port }}
            protocol: TCP
        resources:
{{ toYaml .Values.ui.resources | indent 12 }}
{{- end }}