apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- with .Values.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
        {{- if or .Values.args .Values.cacheAPI.enabled }}
        args:
          {{- if .Values.args }}
          {{- toYaml .Values.args | nindent 10 }}
          {{- end }}
          {{- if .Values.cacheAPI.enabled }}
          {{- if ne .Values.metrics.address "0" }}
          - --metrics-bind-address={{ .Values.metrics.address }}
          {{- end }}
          - --development={{ .Values.development }}
          - --enable-cache-api=true
          - --cache-api-port={{ .Values.cacheAPI.port }}
          - --cache-api-scheme={{ .Values.cacheAPI.scheme }}
          - --cache-api-addr={{ .Values.cacheAPI.address }}
          {{- end }}
        {{- end }}
        env:
          - name: XDS_PORT
            value: "{{ .Values.xds.port }}"
          - name: INSTALLATION_NAMESPACE
            value: {{ .Release.Namespace }}
        {{- if .Values.auth.enabled }}
          - name: OIDC_ENABLED
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_ENABLED
          - name: OIDC_ISSUER_URL
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_ISSUER_URL
          - name: OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_CLIENT_ID
        {{- end }}
        {{- if .Values.auth.acl.nodeIdsByGroup }}
          - name: ACL_CONFIG
            valueFrom:
              configMapKeyRef:
                name: acl
                key: ACL_CONFIG
        {{- end }}
{{/*        {{- if .Values.config }}*/}}
{{/*          - name: CONFIG # TODO: rename*/}}
{{/*            valueFrom:*/}}
{{/*              configMapKeyRef:*/}}
{{/*                name: config*/}}
{{/*                key: CONFIG*/}}
{{/*        {{- end }}*/}}
        {{- with .Values.envs }}
          {{- tpl . $ | nindent 10 }}
        {{- end }}
        {{- if .Values.webhook.enabled }}
          {{- if .Values.webhook.tls.name }}
          - name: TLS_SECRET_NAME
            value: {{ .Values.webhook.tls.name }}
          {{- end }}
          {{- if .Values.webhook.port }}
          - name: WEBHOOK_PORT
            value: "{{ .Values.webhook.port }}"
        {{- end }}
        {{- end }}
        {{- if not .Values.webhook.enabled }}
          - name: WEBHOOK_DISABLE
            value: "true"
        {{- end }}
        {{- if .Values.watchNamespaces }}
          - name: WATCH_NAMESPACES
            value: {{ join "," .Values.watchNamespaces | quote }}
        {{- end }}
        ports:
          - name: grpc
            containerPort: {{ .Values.xds.port }}
            protocol: TCP
            # TODO: hardcode
          - name: webhook-server
            containerPort: 9443
            protocol: TCP
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: envoy-xds-controller
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- /* Volume Mounts */}}
        {{- $mounts := include "chart.volumeMounts" . }}
        {{- if $mounts }}
        volumeMounts:
          {{- $mounts | nindent 10 }}
         {{- end }}
       {{- /* Volumes */}}
       {{- $volumes := include "chart.volumes" . }}
       {{- if $volumes }}
      volumes:
        {{- $volumes | nindent 8 }}
      {{- end }}