apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- with .Values.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
        {{- if .Values.args }}
        args:
          {{- toYaml .Values.args | nindent 10 }}
          {{- if .Values.cacheAPI.enabled }}
          - --development={{ .Values.development }}
          - --enable-cache-api=true
          - --cache-api-port={{ .Values.cacheAPI.port }}
          - --cache-api-scheme={{ .Values.cacheAPI.scheme }}
          - --cache-api-addr={{ .Values.cacheAPI.address }}
          {{- end }}
        {{- else if .Values.cacheAPI.enabled }}
        args:
          - --development={{ .Values.development }}
          - --enable-cache-api=true
          - --cache-api-port={{ .Values.cacheAPI.port }}
          - --cache-api-scheme={{ .Values.cacheAPI.scheme }}
          - --cache-api-addr={{ .Values.cacheAPI.address }}
        {{- end }}
        env:
          - name: XDS_PORT
            value: "{{ .Values.xds.port }}"
          - name: INSTALATION_NAMESPACE
            value: {{ .Release.Namespace }}
        {{- if .Values.auth.enabled }}
          - name: OIDC_ENABLED
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_ENABLED
          - name: OIDC_ISSUER_URL
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_ISSUER_URL
          - name: OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: oidc
                key: OIDC_CLIENT_ID
        {{- end }}
        {{- if .Values.auth.acl.nodeIdsByGroup }}
          - name: ACL_CONFIG
            valueFrom:
              configMapKeyRef:
                name: acl
                key: ACL_CONFIG
        {{- end }}
        {{- with .Values.envs }}
          {{- tpl . $ | nindent 10 }}
        {{- end }}
        {{- if .Values.webhook.enabled }}
        {{- if .Values.webhook.tls.name }}
          - name: TLS_SECRET_NAME
            value: {{ .Values.webhook.tls.name }}
        {{- end }}
        {{- if .Values.webhook.port }}
          - name: WEBHOOK_PORT
            value: "{{ .Values.webhook.port }}"
        {{- end }}
        {{- end }}
        {{- if not .Values.webhook.enabled }}
          - name: WEBHOOK_DISABLE
            value: "true"
        {{- end }}
        {{- if .Values.watchNamespaces }}
          - name: WATCH_NAMESPACES
            value: {{- join "," .Values.watchNamespaces }}
        {{- end }}
        ports:
          - name: grpc
            containerPort: {{ .Values.xds.port }}
            protocol: TCP
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: envoy-xds-controller
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.webhook.enabled }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.webhook.tls.name }}
{{- end }}